# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170606_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.FileField(upload_to=b''),
        ),
    ]
