# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170606_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='User',
        ),
    ]
