# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170607_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytic',
            name='part_concerned',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
