# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_author_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analytic',
            old_name='part_concerned',
            new_name='part',
        ),
        migrations.AlterField(
            model_name='analytic',
            name='Post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
